import {COLORS,id,dateKey,parseDate,addDays,dayDiff,monday,reduce,emptyState} from './model.js';
const $=s=>document.querySelector(s), mode=new URLSearchParams(location.search).get('mode')||'main';
document.title = mode==='todo'?'Monday · 오늘 할 일':mode==='planner'?'Monday · 주간 플래너':'Monday';
let today=dateKey(), selected=today, week=monday(today), page='planner', state, toastTimer, pinned=mode==='todo';
const weekdays=['일','월','화','수','목','금','토'];
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',check:'<path d="m5 12 4 4L19 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M16 3v4M8 3v4M3 11h18"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="m9 5 7 7-7 7"/>',back:'<path d="m15 5-7 7 7 7"/>',monitor:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>',inbox:'<path d="M3 13 6 4h12l3 9v7H3zM3 13h5l2 3h4l2-3h5"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',pin:'<path d="m9 3 6 0-1 6 4 4H6l4-4zM12 13v8"/>',minus:'<path d="M5 12h14"/>',book:'<path d="M4 3h13a3 3 0 0 1 3 3v15H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3M3 17h17M8 3v9l3-2 3 2V3"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z"/>'};
const icon=n=>`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.grid}</svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(d,opts={month:'long',day:'numeric'})=>parseDate(d).toLocaleDateString('ko-KR',opts);
const taskAmount=t=>t.amount?`${t.amount}${esc(t.unit)}`:'개인 할 일';
const count=ts=>`${ts.filter(t=>t.done).length}/${ts.length}`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
async function dispatch(action){try{if(window.desktop)state=await window.desktop.dispatch(action);else{const next=reduce(JSON.parse(localStorage.getItem('monday-state'))||state,action);localStorage.setItem('monday-state',JSON.stringify(next));state=next;}render();return true;}catch(e){toast(e.message);return false;}}
function titlebar(){return `<div class="titlebar"><span>monday<span class="brand-dot">.</span></span><span class="titlebar-caption">${mode==='main'?'플래너':mode==='todo'?'오늘의 할 일':'주간 플래너'}</span><div class="window-controls">${mode!=='main'?`<button title="전체 플래너 열기" data-action="main">${icon('grid')}</button><button title="항상 위에 표시" class="${pinned?'active':''}" data-action="pin">${icon('pin')}</button>`:''}<button title="최소화" data-action="minimize">${icon('minus')}</button><button title="창 닫기" data-action="close">${icon('close')}</button></div></div>`;}
function toolbar(){return `<header class="toolbar"><button class="wordmark" data-action="page" data-page="planner">monday.</button><div class="exam-tabs">${state.exams.map(e=>`<button class="exam-pill" data-action="exam-detail" data-id="${e.id}">${esc(e.name)} <span>${dayDiff(e.start,today)>0?'D-'+dayDiff(e.start,today):e.end>=today?'진행 중':'종료'}</span></button>`).join('')}<button class="text-button" data-action="exam-new">+ 시험 등록</button></div><button class="button small" data-action="widgets">${icon('monitor')} 위젯</button><button class="icon-button" title="설정" data-action="settings">${icon('settings')}</button></header>`;}
function render(){
 const quick=$('#quick-add input'),draft=quick?.value,focused=document.activeElement===quick,caret=quick?.selectionStart;
 document.body.className=`mode-${mode}`;
 $('#app').innerHTML=(window.desktop?titlebar():'')+(mode==='todo'?todoPanel():mode==='planner'?`<main class="widget-planner">${calendarHeader()}${calendar()}</main>`:`${toolbar()}<div class="shell"><main class="main">${page==='exams'?examsPage():plannerPage()}</main>${todoPanel()}</div>`);
 if(draft){const input=$('#quick-add input');if(input){input.value=draft;if(focused){input.focus();input.setSelectionRange(caret,caret);}}}
}
function plannerPage(){return `${calendarHeader()}${calendar()}`;}
function calendarHeader(){const end=addDays(week,6);return `<div class="calendar-header"><div class="month-label"><h1>${parseDate(week).getFullYear()}<span>${parseDate(week).getMonth()+1}월${parseDate(week).getMonth()!==parseDate(end).getMonth()?' — '+(parseDate(end).getMonth()+1)+'월':''}</span></h1></div><div class="calendar-nav"><button class="icon-button" data-action="week-prev" title="이전 주">${icon('back')}</button><button class="button small" data-action="today">오늘</button><button class="icon-button" data-action="week-next" title="다음 주">${icon('arrow')}</button></div></div>`;}
function calendar(){return `<div class="calendar">${Array.from({length:7},(_,i)=>{const date=addDays(week,i),ts=state.tasks.filter(t=>t.date===date).sort((a,b)=>a.done-b.done),exams=state.exams.filter(e=>date>=e.start&&date<=e.end);return `<div class="day-column ${date===today?'is-today':''} ${date===selected?'is-selected':''}" data-date="${date}"><button class="day-heading" data-action="select-day" data-date="${date}"><span class="weekday ${i>4?'weekend':''}">${weekdays[parseDate(date).getDay()]}${date===today?'<small>TODAY</small>':''}</span><span class="day-number">${parseDate(date).getDate()}</span><span class="day-count">${ts.length?count(ts):'—'}</span></button><div class="day-tasks">${exams.map(e=>`<div class="exam-strip">${esc(e.name)}</div>`).join('')}${ts.map(t=>`<button class="plan-card ${t.color} ${t.done?'done':''}" data-action="task-edit" data-id="${t.id}" draggable="true"><span class="card-subject">${esc(t.title)}</span><span class="card-amount">${t.done?icon('check'):''}${taskAmount(t)}</span></button>`).join('')}<button class="add-day" title="${fmt(date)} 할 일 추가" data-action="task-new" data-date="${date}">${icon('plus')}<span>추가</span></button></div></div>`;}).join('')}</div>`;}
function todoPanel(){const ts=state.tasks.filter(t=>t.date===selected),inbox=state.tasks.filter(t=>!t.date&&!t.done),overdue=state.tasks.filter(t=>t.date&&t.date<today&&!t.done);return `<aside class="todo-panel"><div class="todo-heading"><div><h2>${selected===today?'오늘 할 일':fmt(selected)} <small>${count(ts)}</small></h2><button class="icon-button" title="당일 할 일 추가" data-action="task-new" data-date="${selected}">${icon('plus')}</button></div><p>${fmt(selected,{month:'long',day:'numeric',weekday:'short'})}${selected!==today?'<button class="text-button" data-action="today">오늘로</button>':''}</p></div><div class="todo-scroll"><div class="task-list">${[...ts].sort((a,b)=>a.done-b.done).map(t=>todoRow(t)).join('')||'<p class="empty-todo">오늘 할 일이 없어요.</p>'}</div>${overdue.length?`<details class="overdue"><summary>지난 할 일 <b>${overdue.length}</b></summary>${overdue.map(t=>`<div class="inbox-row"><button data-action="task-edit" data-id="${t.id}"><span>${esc(t.title)}</span><small>${fmt(t.date)}</small></button><button title="오늘로 옮기기" class="icon-button" data-action="move-today" data-id="${t.id}">${icon('plus')}</button></div>`).join('')}</details>`:''}<div class="inbox-section"><div class="list-label">나중에 할 일 <span>${inbox.length}</span></div>${inbox.map(t=>`<div class="inbox-row"><button data-action="task-edit" data-id="${t.id}"><span>${esc(t.title)}</span></button><button title="${selected===today?'오늘':fmt(selected)} 할 일로 추가" class="icon-button" data-action="schedule-task" data-id="${t.id}">${icon('plus')}</button></div>`).join('')}<form id="quick-add" class="quick-add"><input name="title" aria-label="나중에 할 일" placeholder="할 일 적어두기" maxlength="100" required autocomplete="off"><button type="submit" title="보관함에 추가" class="icon-button">${icon('plus')}</button></form></div></div></aside>`;}
function todoRow(t){return `<div class="todo-row ${t.done?'done':''}"><button class="checkbox ${t.done?'checked':''}" title="${t.done?'완료 취소':'완료 표시'}: ${esc(t.title)}" data-action="toggle" data-id="${t.id}">${t.done?icon('check'):''}</button><button class="todo-text" data-action="task-edit" data-id="${t.id}"><strong>${esc(t.title)}</strong><span><i class="dot ${t.color}"></i>${taskAmount(t)}</span></button></div>`;}
function examsPage(){return `<header class="page-header"><div><button class="text-button" data-action="page" data-page="planner">← 플래너</button><h1>시험 계획</h1></div><button class="button primary" data-action="exam-new">${icon('plus')}시험 등록</button></header><div class="exam-cards">${state.exams.map(e=>`<article class="exam-detail-card"><div class="exam-card-header"><div><h2>${esc(e.name)}</h2><p>${fmt(e.start)} — ${fmt(e.end)}</p></div><button class="icon-button" title="시험 삭제" data-action="exam-delete" data-id="${e.id}">${icon('trash')}</button></div>${state.subjects.filter(s=>s.examId===e.id).map(s=>{const ts=state.tasks.filter(t=>t.subjectId===s.id),total=ts.reduce((n,t)=>n+(t.amount||0),0),done=ts.filter(t=>t.done).reduce((n,t)=>n+(t.amount||0),0);return `<div class="subject-row"><i class="dot ${s.color}"></i><strong>${esc(s.name)}</strong><span>${s.weekdays.map(n=>weekdays[n]).join(' · ')}</span><b>${done} / ${total}${esc(s.unit)}</b></div>`;}).join('')}<button class="text-button" data-action="subject-new" data-id="${e.id}">${icon('plus')} 과목 & 분량 추가</button><button class="text-button" data-action="exam-week" data-date="${e.start}">시험 주 보기 ${icon('arrow')}</button></article>`).join('')||'<div class="large-empty">시험 주를 등록하면 여기에 과목별 공부 계획이 보여요.</div>'}</div>`;}
function showModal(content){$('#modal').innerHTML=content;$('#modal').showModal();}
function modalHeader(eyebrow,title){return `<div class="modal-header"><div><h2>${title}</h2></div><button class="icon-button" type="button" data-action="modal-close" title="닫기">${icon('close')}</button></div>`;}
function colorPicker(value='lavender'){return `<fieldset class="color-picker"><legend>포인트 색상</legend>${COLORS.map((c,i)=>`<label class="color-option ${c}"><input type="radio" name="color" value="${c}" ${c===value?'checked':''}><span>${icon('check')}</span><b class="sr-only">${['보라','파랑','초록','살구','분홍'][i]}</b></label>`).join('')}</fieldset>`;}
function taskModal(task,date){showModal(`<form id="task-form">${modalHeader(task?.subjectId?'STUDY PLAN':'TO-DO',task?'할 일 수정':'새로운 할 일')}<p class="modal-intro">${task?.subjectId?'여기서 바꾸는 날짜와 분량은 플래너에도 바로 반영돼요.':'오늘 할 일도, 나중에 할 일도 가볍게 적어두세요.'}</p><label>할 일<input name="title" placeholder="예: 수학 오답 노트 정리하기" value="${esc(task?.title)}" maxlength="100" required autofocus></label><div class="form-grid"><label>날짜 <span class="muted">비워두면 보관함</span><input name="date" type="date" value="${esc(task?task.date:date)}"></label><label>분량 <span class="muted">선택</span><div class="amount-input"><input name="amount" aria-label="분량" type="number" min="1" max="100000" value="${task?.amount||''}" placeholder="20"><input name="unit" aria-label="단위" maxlength="10" value="${esc(task?.unit||'쪽')}" placeholder="쪽"></div></label></div>${colorPicker(task?.color)}<div class="form-actions">${task?`<button type="button" class="text-button danger" data-action="task-delete" data-id="${task.id}">${icon('trash')}삭제</button>`:''}<button type="button" class="button" data-action="modal-close">취소</button><button class="button primary" type="submit">${task?'변경 저장':'할 일 추가'}</button></div></form>`);$('#task-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(await dispatch({type:'task-save',task:{...(task?{id:task.id}:{id:id(),done:false}),title:f.get('title').trim(),date:f.get('date'),amount:f.get('amount')?Number(f.get('amount')):null,unit:f.get('unit').trim(),color:f.get('color')}})){$('#modal').close();toast('할 일과 플래너에 저장했어요.');}};}
function subjectFields(index=0){return `<div class="subject-fields"><div class="subject-field-title"><strong>공부할 과목</strong>${index?'<button type="button" class="text-button" data-action="remove-subject">제거</button>':''}</div><div class="form-grid subject-inputs"><label>과목<input name="subject-name" placeholder="예: 수학" maxlength="40" required></label><label>총 공부량<input name="total" type="number" placeholder="120" min="1" max="100000" required></label><label>단위<select name="unit"><option>쪽</option><option>문제</option><option>단어</option><option>강</option><option>회</option><option>시간</option></select></label><label>색상<select name="subject-color">${COLORS.map((c,i)=>`<option value="${c}" ${i===index%5?'selected':''}>${['보라','파랑','초록','살구','분홍'][i]}</option>`).join('')}</select></label></div><fieldset class="weekday-picker"><legend>공부할 요일</legend>${[1,2,3,4,5,6,0].map(n=>`<label><input type="checkbox" name="weekday" value="${n}" ${[1,3,5].includes(n)?'checked':''}><span>${weekdays[n]}</span></label>`).join('')}</fieldset></div>`;}
function examModal(exam){showModal(`<form id="exam-form">${modalHeader('MAKE A STUDY PLAN',exam?'공부할 과목 추가':'새로운 시험 계획')}<p class="modal-intro">공부할 요일을 고르면 시험 전날까지 분량을 골고루 나눠요.</p>${!exam?'<label>시험 이름<input name="name" placeholder="예: 2학기 중간고사" maxlength="60" required autofocus></label><div class="form-grid"><label>시험 시작일<input type="date" name="start" required></label><label>시험 마지막 날<input type="date" name="end" required></label></div>':`<div class="exam-info">${esc(exam.name)} · ${fmt(exam.start)} 시작</div>`}<label>공부 시작일<input type="date" name="study-start" value="${today}" required></label><div id="subjects">${subjectFields()}</div>${!exam?`<button type="button" class="button add-subject" data-action="add-subject">${icon('plus')}과목 추가</button>`:''}<div class="distribution-note">${icon('spark')} 분량은 정수로 나누고, 남는 분량은 앞 날짜부터 배정해요.</div><div class="form-actions"><button type="button" class="button" data-action="modal-close">취소</button><button type="submit" class="button primary">분량 나누고 저장 ${icon('arrow')}</button></div></form>`);const form=$('#exam-form');if(!exam){form.elements.start.onchange=()=>{if(!form.elements.end.value||form.elements.end.value<form.elements.start.value)form.elements.end.value=addDays(form.elements.start.value,4);};}form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),examData=exam||{id:id(),name:f.get('name').trim(),start:f.get('start'),end:f.get('end')};const subjects=[...form.querySelectorAll('.subject-fields')].map(el=>({name:el.querySelector('[name="subject-name"]').value,total:Number(el.querySelector('[name="total"]').value),unit:el.querySelector('[name="unit"]').value,color:el.querySelector('[name="subject-color"]').value,start:f.get('study-start'),weekdays:[...el.querySelectorAll('[name="weekday"]:checked')].map(n=>Number(n.value))}));if(await dispatch(exam?{type:'subject-add',examId:exam.id,subject:subjects[0]}:{type:'exam-add',exam:examData,subjects})){$('#modal').close();toast('공부 분량을 나눠 플래너에 담았어요.');}};}
function confirmModal(title,body,action){showModal(`${modalHeader('PLEASE CHECK',title)}<p class="modal-intro">${body}</p><div class="form-actions"><button class="button" data-action="modal-close">취소</button><button id="confirm-button" class="button primary">확인</button></div>`);$('#confirm-button').onclick=async()=>{if(await action())$('#modal').close();};}
async function windowAction(action){if(window.desktop){const result=await window.desktop.windowAction(action);if(action==='pin'){pinned=result;render();}return result;}if(action==='widgets'){showModal(`${modalHeader('DESKTOP WIDGETS','바탕화면에 가까이')}<p class="modal-intro">Windows 앱에서 주간 플래너와 우측 할 일 위젯을 독립된 창으로 사용할 수 있어요. 아래에서 위젯 화면을 미리 볼 수 있어요.</p><div class="preview-links"><a class="button" href="?mode=planner" target="_blank">플래너 미리보기</a><a class="button primary" href="?mode=todo" target="_blank">할 일 미리보기</a></div>`);}else if(action==='main')location.href='?mode=main';else toast('창 제어 기능은 Windows 앱에서 사용할 수 있어요.');}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();const a=b.dataset.action,tid=b.dataset.id;
  if(['widgets','main','minimize','close','pin','dock','quit'].includes(a))return windowAction(a);
  if(a==='page'){page=b.dataset.page;render();}
  if(a==='week-prev'||a==='week-next'){week=addDays(week,a==='week-prev'?-7:7);render();}
  if(a==='today'){selected=today;week=monday(today);render();}
  if(a==='select-day'){selected=b.dataset.date;render();}
  if(a==='exam-week'){week=monday(b.dataset.date);page='planner';render();}
  if(a==='task-new')taskModal(null,b.dataset.date??selected);
  if(a==='task-edit')taskModal(state.tasks.find(t=>t.id===tid));
  if(a==='toggle')await dispatch({type:'task-toggle',id:tid});
  if(a==='schedule-task'||a==='move-today'){if(await dispatch({type:'task-date',id:tid,date:a==='move-today'?today:selected}))toast('할 일과 플래너에 추가했어요.');}
  if(a==='task-delete')confirmModal('할 일을 삭제할까요?','연결된 플래너에서도 이 일정이 삭제돼요.',()=>dispatch({type:'task-delete',id:tid}));
  if(a==='exam-delete')confirmModal('시험 계획을 삭제할까요?','이 시험의 과목과 연결된 공부 일정이 함께 삭제돼요. 개인 할 일은 유지돼요.',()=>dispatch({type:'exam-delete',id:tid}));
  if(a==='exam-new')examModal();
  if(a==='exam-detail'){page='exams';render();}
  if(a==='subject-new')examModal(state.exams.find(e=>e.id===tid));
  if(a==='modal-close')$('#modal').close();
  if(a==='add-subject')$('#subjects').insertAdjacentHTML('beforeend',subjectFields($('#subjects').children.length));
  if(a==='remove-subject')b.closest('.subject-fields').remove();
  if(a==='settings')showModal(`${modalHeader('YOUR WORKSPACE','설정 & 데이터')}<div class="settings-row"><div><strong>바탕화면 위젯</strong><p>주간 플래너 + 우측에 붙는 할 일 목록</p></div><button class="button" data-action="widgets">위젯 열기</button></div><div class="settings-row"><div><strong>데이터 백업</strong><p>현재 계획을 JSON 파일로 저장해요.</p></div><button class="button" data-action="backup">${icon('download')}백업</button></div><p class="helper">변경 내용은 이 PC에 자동 저장돼요. 위젯 상단의 핀을 누르면 다른 창 위에 고정할 수 있어요. 플래너 위젯은 제목 표시줄로 이동할 수 있어요.</p>${window.desktop?'<button class="text-button danger" data-action="quit">앱 완전히 종료</button>':''}`);
  if(a==='backup'){if(window.desktop){if(await window.desktop.backup())toast('백업 파일을 저장했어요.');}else{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`Monday-${today}.json`;anchor.click();URL.revokeObjectURL(url);toast('백업 파일을 저장했어요.');}}
});
document.addEventListener('submit',async e=>{if(e.target.id!=='quick-add')return;e.preventDefault();const title=new FormData(e.target).get('title').trim();if(!title)return;e.target.reset();if(await dispatch({type:'task-save',task:{id:id(),title,date:'',amount:null,unit:'',done:false,color:'lavender'}}))$('#quick-add input')?.focus();else $('#quick-add input').value=title;});
document.addEventListener('dragstart',e=>{const card=e.target.closest('.plan-card');if(card)e.dataTransfer.setData('text/plain',card.dataset.id);});
document.addEventListener('dragover',e=>{if(e.target.closest('.day-column')){e.preventDefault();e.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',async e=>{const day=e.target.closest('.day-column');if(day){e.preventDefault();await dispatch({type:'task-date',id:e.dataTransfer.getData('text/plain'),date:day.dataset.date});}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
try{if(window.desktop){state=await window.desktop.getState();window.desktop.onChange(next=>{state=next;render();});}else{const stored=localStorage.getItem('monday-state');state=stored?JSON.parse(stored):emptyState();if(!stored)localStorage.setItem('monday-state',JSON.stringify(state));window.addEventListener('storage',e=>{if(e.key==='monday-state'&&e.newValue){state=JSON.parse(e.newValue);render();}});}render();}catch(e){$('#app').textContent='저장된 계획을 불러오지 못했어요. 원본 데이터를 보존하고 앱을 다시 열어 주세요. '+e.message;}
setInterval(()=>{const now=dateKey();if(today!==now){if(selected===today)selected=now;today=now;render();}},30000);
