import {COLORS,SCOPE_UNITS,PRIORITIES,studyDays,compareSubjects,scopeLabel,distribute,id,dateKey,parseDate,addDays,dayDiff,monday,reduce,emptyState} from './model.js';
const $=s=>document.querySelector(s), mode=new URLSearchParams(location.search).get('mode')||'main';
document.title = mode==='todo'?'Monday · 오늘 할 일':mode==='planner'?'Monday · 주간 플래너':'Monday';
let today=dateKey(), selected=today, week=monday(today), page='planner', state, toastTimer, pinned=mode==='todo';
const weekdays=['일','월','화','수','목','금','토'];
const icons={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',check:'<path d="m5 12 4 4L19 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M16 3v4M8 3v4M3 11h18"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="m9 5 7 7-7 7"/>',back:'<path d="m15 5-7 7 7 7"/>',monitor:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/>',inbox:'<path d="M3 13 6 4h12l3 9v7H3zM3 13h5l2 3h4l2-3h5"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',pin:'<path d="m9 3 6 0-1 6 4 4H6l4-4zM12 13v8"/>',minus:'<path d="M5 12h14"/>',book:'<path d="M4 3h13a3 3 0 0 1 3 3v15H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3M3 17h17M8 3v9l3-2 3 2V3"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z"/>'};
const icon=n=>`<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.grid}</svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(d,opts={month:'long',day:'numeric'})=>parseDate(d).toLocaleDateString('ko-KR',opts);
const taskAmount=t=>t.round?`${t.round}회독 · ${esc(scopeLabel(t.rangeStart,t.rangeEnd,t.unit))}${t.details?' · '+esc(t.details):''}`:t.details?esc(t.details):t.amount?`${t.amount}${esc(t.unit)}`:'개인 할 일';
const dday=date=>dayDiff(date,today)>0?'D-'+dayDiff(date,today):date===today?'D-day':'시험 종료';
const exactDate=d=>fmt(d,{year:'numeric',month:'long',day:'numeric',weekday:'short'});
const priorityOptions=(value='auto')=>Object.entries(PRIORITIES).map(([key,label])=>`<option value="${key}" ${key===value?'selected':''}>${label}${key==='auto'?' · 공부할 날이 적은 순':''}</option>`).join('');
function compareTasks(a,b){const sa=state.subjects.find(s=>s.id===a.subjectId),sb=state.subjects.find(s=>s.id===b.subjectId);return Number(Boolean(a.done))-Number(Boolean(b.done))||(sa&&sb?compareSubjects(sa,sb,today):Number(!sa)-Number(!sb))||(a.round||0)-(b.round||0)||(a.session||0)-(b.session||0);}
function taskDeadline(t){const subject=state.subjects.find(s=>s.id===t.subjectId);return subject?.examDate?`<small class="task-deadline">${fmt(subject.examDate)} 시험 · ${dday(subject.examDate)} · ${PRIORITIES[subject.priority||'auto']}</small>`:'';}
const count=ts=>`${ts.filter(t=>t.done).length}/${ts.length}`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
async function dispatch(action){try{if(window.desktop)state=await window.desktop.dispatch(action);else{const next=reduce(JSON.parse(localStorage.getItem('monday-state'))||state,action);localStorage.setItem('monday-state',JSON.stringify(next));state=next;}render();return true;}catch(e){toast(e.message);return false;}}
function titlebar(){return `<div class="titlebar"><span>monday<span class="brand-dot">.</span></span><span class="titlebar-caption">${mode==='main'?'플래너':mode==='todo'?'오늘의 할 일':'주간 플래너'}</span><div class="window-controls">${mode!=='main'?`<button title="전체 플래너 열기" data-action="main">${icon('grid')}</button><button title="항상 위에 표시" class="${pinned?'active':''}" data-action="pin">${icon('pin')}</button>`:''}<button title="최소화" data-action="minimize">${icon('minus')}</button><button title="창 닫기" data-action="close">${icon('close')}</button></div></div>`;}
function toolbar(){return `<header class="toolbar"><button class="wordmark" data-action="page" data-page="planner">monday.</button><div class="exam-tabs">${state.exams.map(e=>`<button class="exam-pill" data-action="exam-detail" data-id="${e.id}">${esc(e.name)} <span>${dayDiff(e.start,today)>0?'D-'+dayDiff(e.start,today):e.end>=today?'진행 중':'종료'}</span></button>`).join('')}<button class="text-button" data-action="exam-new">+ 시험 등록</button></div><button class="button small" data-action="widgets">${icon('monitor')} 위젯</button><button class="icon-button" title="설정" data-action="settings">${icon('settings')}</button></header>`;}
function render(){
 const quick=$('#quick-add input'),draft=quick?.value,focused=document.activeElement===quick,caret=quick?.selectionStart;
 document.body.className=`mode-${mode}`;
 $('#app').innerHTML=(window.desktop?titlebar():'')+(mode==='todo'?todoPanel():mode==='planner'?`<main class="widget-planner">${calendarHeader()}${calendar()}</main>`:`${toolbar()}<div class="shell"><main class="main">${page==='exams'?examsPage():plannerPage()}</main>${todoPanel()}</div>`);
 if(draft){const input=$('#quick-add input');if(input){input.value=draft;if(focused){input.focus();input.setSelectionRange(caret,caret);}}}
}
function plannerPage(){return `${studyOverview()}${calendarHeader()}${calendar()}`;}
function subjectComplete(subject){const tasks=state.tasks.filter(t=>t.subjectId===subject.id);return tasks.length>0&&tasks.every(t=>t.done);}
function studyOverview(){
 const subjects=state.subjects.filter(s=>s.examDate>=today).sort((a,b)=>Number(subjectComplete(a))-Number(subjectComplete(b))||compareSubjects(a,b,today));
 return subjects.length?`<div class="priority-heading"><strong>먼저 공부할 과목</strong><span>높음 → 자동·보통 → 낮음 · 같은 중요도에서는 공부할 날이 적은 순</span></div><div class="study-overview">${subjects.map((s,i)=>{const ts=state.tasks.filter(t=>t.subjectId===s.id),complete=ts.length&&ts.every(t=>t.done);return `<button class="study-summary" data-action="subject-settings" data-id="${s.id}"><span class="study-countdown">${dday(s.examDate)}</span><strong>${complete?'완료 ·':(i+1)+'.'} ${esc(s.name)}</strong><span>${exactDate(s.examDate)} 시험</span><span class="priority-label">중요도 ${PRIORITIES[s.priority||'auto']} · 공부할 수 있는 날 ${studyDays(s,today)}일</span><span>${s.rounds?esc(scopeLabel(s.rangeStart,s.rangeEnd,s.unit))+' · '+s.rounds+'회독 목표':'기존 공부 계획'}</span><small>${complete?'공부 완료':count(ts)+'회 공부 완료'} · 시험일·중요도 수정</small></button>`;}).join('')}</div>`:!state.exams.length?`<div class="study-empty"><div><strong>시험일과 범위만 정해도 시작할 수 있어요.</strong><p>단원·챕터·주차를 나누고, 남은 날에 맞춰 회독 일정을 자동으로 짜드려요.</p></div><button class="button primary" data-action="exam-new">시험 계획 세우기</button></div>`:'';
}
function calendarHeader(){const end=addDays(week,6);return `<div class="calendar-header"><div class="month-label"><h1>${parseDate(week).getFullYear()}<span>${parseDate(week).getMonth()+1}월${parseDate(week).getMonth()!==parseDate(end).getMonth()?' — '+(parseDate(end).getMonth()+1)+'월':''}</span></h1></div><div class="calendar-nav"><button class="icon-button" data-action="week-prev" title="이전 주">${icon('back')}</button><button class="button small" data-action="today">오늘</button><button class="icon-button" data-action="week-next" title="다음 주">${icon('arrow')}</button></div></div>`;}
function calendar(){return `<div class="calendar">${Array.from({length:7},(_,i)=>{const date=addDays(week,i),ts=state.tasks.filter(t=>t.date===date).sort(compareTasks),exams=state.exams.filter(e=>date>=e.start&&date<=e.end);return `<div class="day-column ${date===today?'is-today':''} ${date===selected?'is-selected':''}" data-date="${date}"><button class="day-heading" data-action="select-day" data-date="${date}"><span class="weekday ${i>4?'weekend':''}">${weekdays[parseDate(date).getDay()]}${date===today?'<small>TODAY</small>':''}</span><span class="day-number">${parseDate(date).getDate()}</span><span class="day-count">${ts.length?count(ts):'—'}</span></button><div class="day-tasks">${exams.map(e=>`<div class="exam-strip">${esc(e.name)}</div>`).join('')}${state.subjects.filter(s=>s.examDate===date).map(s=>`<div class="subject-exam">${esc(s.name)} 시험</div>`).join('')}${ts.map(t=>`<button class="plan-card ${t.color} ${t.done?'done':''}" data-action="task-edit" data-id="${t.id}" draggable="true"><span class="card-subject">${esc(t.title)}</span><span class="card-amount">${t.done?icon('check'):''}${taskAmount(t)}</span>${taskDeadline(t)}</button>`).join('')}<button class="add-day" title="${fmt(date)} 할 일 추가" data-action="task-new" data-date="${date}">${icon('plus')}<span>추가</span></button></div></div>`;}).join('')}</div>`;}
function todoPanel(){const ts=state.tasks.filter(t=>t.date===selected),inbox=state.tasks.filter(t=>!t.date&&!t.done),overdue=state.tasks.filter(t=>t.date&&t.date<today&&!t.done);return `<aside class="todo-panel"><div class="todo-heading"><div><h2>${selected===today?'오늘 할 일':fmt(selected)} <small>${count(ts)}</small></h2><button class="icon-button" title="당일 할 일 추가" data-action="task-new" data-date="${selected}">${icon('plus')}</button></div><p>${fmt(selected,{month:'long',day:'numeric',weekday:'short'})}${selected!==today?'<button class="text-button" data-action="today">오늘로</button>':''}</p></div><div class="todo-scroll"><div class="task-list">${[...ts].sort(compareTasks).map(t=>todoRow(t)).join('')||'<p class="empty-todo">오늘 할 일이 없어요.</p>'}</div>${overdue.length?`<details class="overdue"><summary>지난 할 일 <b>${overdue.length}</b></summary>${overdue.map(t=>`<div class="inbox-row"><button data-action="task-edit" data-id="${t.id}"><span>${esc(t.title)}</span><small>${fmt(t.date)}</small></button><button title="오늘로 옮기기" class="icon-button" data-action="move-today" data-id="${t.id}">${icon('plus')}</button></div>`).join('')}</details>`:''}<div class="inbox-section"><div class="list-label">나중에 할 일 <span>${inbox.length}</span></div>${inbox.map(t=>`<div class="inbox-row"><button data-action="task-edit" data-id="${t.id}"><span>${esc(t.title)}</span></button><button title="${selected===today?'오늘':fmt(selected)} 할 일로 추가" class="icon-button" data-action="schedule-task" data-id="${t.id}">${icon('plus')}</button></div>`).join('')}<form id="quick-add" class="quick-add"><input name="title" aria-label="나중에 할 일" placeholder="할 일 적어두기" maxlength="100" required autocomplete="off"><button type="submit" title="보관함에 추가" class="icon-button">${icon('plus')}</button></form></div></div></aside>`;}
function todoRow(t){return `<div class="todo-row ${t.done?'done':''}"><button class="checkbox ${t.done?'checked':''}" title="${t.done?'완료 취소':'완료 표시'}: ${esc(t.title)}" data-action="toggle" data-id="${t.id}">${t.done?icon('check'):''}</button><button class="todo-text" data-action="task-edit" data-id="${t.id}"><strong>${esc(t.title)}</strong><span><i class="dot ${t.color}"></i>${taskAmount(t)}</span>${taskDeadline(t)}</button></div>`;}
function examsPage(){return `<header class="page-header"><div><button class="text-button" data-action="page" data-page="planner">← 플래너</button><h1>시험 계획</h1></div><button class="button primary" data-action="exam-new">시험 등록</button></header><div class="exam-cards">${state.exams.map(e=>`<article class="exam-detail-card"><div class="exam-card-header"><div><h2>${esc(e.name)}</h2><p>${fmt(e.start)} — ${fmt(e.end)}</p></div><button class="icon-button" title="시험 삭제" data-action="exam-delete" data-id="${e.id}">${icon('trash')}</button></div>${state.subjects.filter(s=>s.examId===e.id).sort((a,b)=>compareSubjects(a,b,today)).map(s=>{const ts=state.tasks.filter(t=>t.subjectId===s.id);return `<div class="subject-progress"><div class="subject-row"><i class="dot ${s.color}"></i><strong>${esc(s.name)}</strong><span>${s.examDate?dday(s.examDate)+' · '+exactDate(s.examDate):'시험일 미설정'}</span><b>${count(ts)}회 완료</b></div><div class="subject-controls"><span>중요도 ${PRIORITIES[s.priority||'auto']}</span><button class="text-button" data-action="subject-settings" data-id="${s.id}">시험일·중요도 / 자동 배치</button></div>${s.rounds?`<p>${esc(scopeLabel(s.rangeStart,s.rangeEnd,s.unit))} · 한 회독을 ${s.splits}번으로 · 총 ${s.rounds}회독</p><div class="round-progress">${Array.from({length:s.rounds},(_,i)=>{const tasks=ts.filter(t=>t.round===i+1);return `<span>${i+1}회독 <b>${count(tasks)}</b></span>`;}).join('')}</div>`:''}</div>`;}).join('')}<button class="text-button" data-action="subject-new" data-id="${e.id}">${icon('plus')} 과목별 회독 계획 추가</button><button class="text-button" data-action="exam-week" data-date="${e.start}">시험 주 보기 ${icon('arrow')}</button></article>`).join('')||'<div class="large-empty">시험을 등록하고 과목별 회독 계획을 세워보세요.</div>'}</div>`;}
function showModal(content){$('#modal').innerHTML=content;$('#modal').showModal();}
function modalHeader(eyebrow,title){return `<div class="modal-header"><div><h2>${title}</h2></div><button class="icon-button" type="button" data-action="modal-close" title="닫기">${icon('close')}</button></div>`;}
function colorPicker(value='lavender'){return `<fieldset class="color-picker"><legend>포인트 색상</legend>${COLORS.map((c,i)=>`<label class="color-option ${c}"><input type="radio" name="color" value="${c}" ${c===value?'checked':''}><span>${icon('check')}</span><b class="sr-only">${['보라','파랑','초록','살구','분홍'][i]}</b></label>`).join('')}</fieldset>`;}
function taskModal(task,date){
 const study=Boolean(task?.round),legacy=Boolean(task?.amount&&!study);
 showModal(`<form id="task-form">${modalHeader('',task?'할 일 수정':'새로운 할 일')}<p class="modal-intro">${study?task.round+'회독 · 날짜와 공부 범위를 조정할 수 있어요.':'공부할 내용이나 개인 할 일을 적어두세요.'}</p><label>할 일<input name="title" placeholder="예: 전공 강의 필기 정리" value="${esc(task?.title)}" maxlength="100" required autofocus></label><label>날짜 <span class="muted">비워두면 나중에 할 일</span><input name="date" type="date" value="${esc(task?task.date:date)}"></label>${study?`<div class="form-grid"><label>시작 ${esc(task.unit)}<input name="rangeStart" type="number" min="1" max="1000" value="${task.rangeStart}" required></label><label>끝 ${esc(task.unit)}<input name="rangeEnd" type="number" min="1" max="1000" value="${task.rangeEnd}" required></label></div>`:legacy?`<label>분량<div class="amount-input"><input name="amount" aria-label="분량" type="number" min="1" max="100000" value="${task.amount}"><input name="unit" aria-label="단위" maxlength="10" value="${esc(task.unit)}"></div></label>`:''}<label>공부 범위 / 메모 <span class="muted">선택</span><input name="details" maxlength="200" value="${esc(task?.details)}" placeholder="예: 3주차 수요·공급, 강의 노트 정리"></label>${colorPicker(task?.color)}<div class="form-actions">${task?`<button type="button" class="text-button danger" data-action="task-delete" data-id="${task.id}">삭제</button>`:''}<button type="button" class="button" data-action="modal-close">취소</button><button class="button primary" type="submit">${task?'변경 저장':'할 일 추가'}</button></div></form>`);
 $('#task-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),rangeStart=Number(f.get('rangeStart')),rangeEnd=Number(f.get('rangeEnd'));if(await dispatch({type:'task-save',task:{...(task?{id:task.id}:{id:id(),done:false}),title:f.get('title').trim(),date:f.get('date'),details:f.get('details').trim(),...(study?{rangeStart,rangeEnd,amount:rangeEnd-rangeStart+1}:legacy?{amount:f.get('amount')?Number(f.get('amount')):null,unit:f.get('unit').trim()}:{}),color:f.get('color')}})){$('#modal').close();toast('할 일과 플래너에 저장했어요.');}};
}
function subjectFields(index=0){return `<div class="subject-fields"><div class="subject-field-title"><strong>과목별 회독 계획</strong>${index?'<button type="button" class="text-button" data-action="remove-subject">제거</button>':''}</div><div class="form-grid"><label>과목<input name="subject-name" placeholder="예: 미시경제학" maxlength="40" required></label><label>과목 시험일<input name="exam-date" type="date" required></label></div><div class="form-grid scope-inputs"><label>범위 구분<select name="unit">${SCOPE_UNITS.map(u=>`<option>${u}</option>`).join('')}</select></label><label>시작 번호<input name="range-start" type="number" value="1" min="1" max="1000" required></label><label>끝 번호<input name="range-end" type="number" placeholder="8" min="1" max="1000" required></label></div><div class="form-grid"><label>한 회독을 나눌 횟수 <span class="muted">선택</span><input name="splits" type="number" placeholder="비워두면 남은 날에 맞춰 자동" min="1" max="1000"></label><label>목표 회독 수<input name="rounds" type="number" value="2" min="1" max="20" required></label></div><div class="form-grid"><label>중요도<select name="priority">${priorityOptions()}</select></label><label>색상<select name="subject-color">${COLORS.map((c,i)=>`<option value="${c}" ${i===index%5?'selected':''}>${['보라','파랑','초록','살구','분홍'][i]}</option>`).join('')}</select></label></div><div class="plan-preview" aria-live="polite">시험일과 범위를 입력하면 회독 일정을 미리 볼 수 있어요.</div></div>`;}
function readSubjects(form){return [...form.querySelectorAll('.subject-fields')].map(el=>({name:el.querySelector('[name="subject-name"]').value,rangeStart:Number(el.querySelector('[name="range-start"]').value),rangeEnd:Number(el.querySelector('[name="range-end"]').value),unit:el.querySelector('[name="unit"]').value,splits:el.querySelector('[name="splits"]').value?Number(el.querySelector('[name="splits"]').value):null,priority:el.querySelector('[name="priority"]').value,rounds:Number(el.querySelector('[name="rounds"]').value),examDate:el.querySelector('[name="exam-date"]').value,color:el.querySelector('[name="subject-color"]').value,start:form.elements['study-start'].value}));}
function previewPlans(form,exam){
 const examData=exam||{id:'preview',start:form.elements.start.value,end:form.elements.end.value};
 const subjects=readSubjects(form);
 form.querySelectorAll('.subject-fields').forEach((el,i)=>{
  const input=subjects[i],dateInput=el.querySelector('[name="exam-date"]');dateInput.min=examData.start;dateInput.max=examData.end;
  const preview=el.querySelector('.plan-preview');
  if(!input.examDate||!input.rangeEnd||!input.start){preview.textContent='시험일과 범위를 입력하면 회독 일정을 미리 볼 수 있어요.';return;}
  try{const {subject,tasks}=distribute({...input,name:input.name||'과목'},examData),days=dayDiff(input.examDate,input.start),maxDaily=Math.max(...Object.values(tasks.reduce((counts,t)=>(counts[t.date]=(counts[t.date]||0)+1,counts),{})));
   preview.innerHTML=`<strong>${exactDate(input.examDate)} 시험 · ${dday(input.examDate)}</strong><p>${days}일 동안 총 ${tasks.length}번 공부 · 중요도 ${PRIORITIES[subject.priority]}</p><p>${esc(scopeLabel(input.rangeStart,input.rangeEnd,input.unit))} · ${subject.autoSplit?'자동 분할 · ':''}${subject.splits}번으로 나눠 ${input.rounds}회독${maxDaily>1?' · 하루 최대 '+maxDaily+'번':''}</p><div class="preview-rounds">${Array.from({length:input.rounds},(_,i)=>{const roundTasks=tasks.filter(t=>t.round===i+1);return `<span>${i+1}회독 <b>${fmt(roundTasks[0].date)} — ${fmt(roundTasks.at(-1).date)}</b></span>`;}).join('')}</div><small>첫 공부: ${fmt(tasks[0].date)} · 1회독 · ${esc(scopeLabel(tasks[0].rangeStart,tasks[0].rangeEnd,input.unit))}</small>`;
  }catch(error){preview.textContent=error.message;}
 });
}
function examModal(exam){
 showModal(`<form id="exam-form">${modalHeader('',exam?'과목별 회독 계획 추가':'시험까지, 몇 회독 할까요?')}<p class="modal-intro">과목별 시험일과 범위, 목표 회독을 입력하세요. 나눌 횟수를 비워두면 남은 공부일에 맞춰 범위와 날짜를 자동으로 정해요.</p>${!exam?'<label>시험 이름<input name="name" placeholder="예: 2학기 중간고사" maxlength="60" required autofocus></label><div class="form-grid"><label>시험 기간 시작<input type="date" name="start" required></label><label>시험 기간 끝<input type="date" name="end" required></label></div>':`<div class="exam-info">${esc(exam.name)} · ${fmt(exam.start)} — ${fmt(exam.end)}</div>`}<label>공부 시작일<input type="date" name="study-start" value="${today}" required></label><div id="subjects">${subjectFields()}</div>${!exam?`<button type="button" class="button add-subject" data-action="add-subject">${icon('plus')}과목 추가</button>`:''}<div class="distribution-note">${icon('spark')} 1회독을 마친 뒤 2회독으로 이어져요. 저장 후 날짜와 범위를 직접 조정할 수 있어요.</div><div class="form-actions"><button type="button" class="button" data-action="modal-close">취소</button><button type="submit" class="button primary">회독 계획 저장 ${icon('arrow')}</button></div></form>`);
 const form=$('#exam-form');
 if(exam)form.querySelector('[name="exam-date"]').value=exam.start;
 form.oninput=()=>previewPlans(form,exam);
 form.onchange=e=>{if(!exam&&e.target.name==='start'){if(!form.elements.end.value||form.elements.end.value<form.elements.start.value)form.elements.end.value=form.elements.start.value;for(const el of form.querySelectorAll('[name="exam-date"]'))if(!el.value)el.value=form.elements.start.value;}previewPlans(form,exam);};
 previewPlans(form,exam);
 form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form),examData=exam||{id:id(),name:f.get('name').trim(),start:f.get('start'),end:f.get('end')},subjects=readSubjects(form);if(await dispatch(exam?{type:'subject-add',examId:exam.id,subject:subjects[0]}:{type:'exam-add',exam:examData,subjects})){$('#modal').close();week=monday(subjects[0].start);selected=subjects[0].start;page='planner';render();toast('시험일까지의 회독 계획을 만들었어요.');}};
}
function subjectSettings(subject){
 const exam=state.exams.find(e=>e.id===subject.examId),start=subject.start>today?subject.start:today;
 const pending=state.tasks.filter(t=>t.subjectId===subject.id&&!t.done);
 showModal(`<form id="subject-settings-form">${modalHeader('',esc(subject.name))}<p class="modal-intro">높음은 먼저, 낮음은 나중에 표시해요. 자동·보통 과목은 공부할 수 있는 날이 적은 순으로 추천해요.</p><div class="form-grid"><label>과목 시험일<input type="date" name="exam-date" value="${subject.examDate||exam.start}" min="${exam.start}" max="${exam.end}" required></label><label>중요도<select name="priority">${priorityOptions(subject.priority)}</select></label></div><p id="subject-deadline" class="exam-info"></p><label>자동 배치 시작일<input type="date" name="study-start" value="${start}" required></label><label class="replan-choice"><input type="checkbox" name="replan">미완료 공부 ${pending.length}회를 시험 전날까지 다시 자동 배치</label><p class="helper">시험일을 바꾸면 미완료 공부를 새 시험일에 맞춰 다시 배치해요. 완료한 공부와 각 회독의 범위는 유지돼요.</p><div class="form-actions"><button type="button" class="button" data-action="modal-close">취소</button><button type="submit" class="button primary">변경 저장</button></div></form>`);
 const form=$('#subject-settings-form');
 const update=()=>{const date=form.elements['exam-date'].value;$('#subject-deadline').textContent=date?exactDate(date)+' 시험 · '+dday(date)+' · 공부할 수 있는 날 '+studyDays({...subject,examDate:date,start:form.elements['study-start'].value},today)+'일':'시험일을 입력해 주세요.';};
 form.oninput=update;update();
 form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);if(await dispatch({type:'subject-update',id:subject.id,examDate:f.get('exam-date'),priority:f.get('priority'),start:f.get('study-start'),replan:f.has('replan')})){$('#modal').close();toast('시험일과 중요도를 반영했어요.');}};
}
function confirmModal(title,body,action){showModal(`${modalHeader('PLEASE CHECK',title)}<p class="modal-intro">${body}</p><div class="form-actions"><button class="button" data-action="modal-close">취소</button><button id="confirm-button" class="button primary">확인</button></div>`);$('#confirm-button').onclick=async()=>{if(await action())$('#modal').close();};}
async function windowAction(action){if(window.desktop){const result=await window.desktop.windowAction(action);if(action==='pin'){pinned=result;render();}return result;}if(action==='widgets'){showModal(`${modalHeader('DESKTOP WIDGETS','바탕화면에 가까이')}<p class="modal-intro">Windows 앱에서 주간 플래너와 우측 할 일 위젯을 독립된 창으로 사용할 수 있어요. 아래에서 위젯 화면을 미리 볼 수 있어요.</p><div class="preview-links"><a class="button" href="?mode=planner" target="_blank">플래너 미리보기</a><a class="button primary" href="?mode=todo" target="_blank">할 일 미리보기</a></div>`);}else if(action==='main')location.href='?mode=main';else toast('창 제어 기능은 Windows 앱에서 사용할 수 있어요.');}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();const a=b.dataset.action,tid=b.dataset.id;
  if(['widgets','main','minimize','close','pin','dock','quit'].includes(a))return windowAction(a);
  if(a==='page'){page=b.dataset.page;render();}
  if(a==='week-prev'||a==='week-next'){week=addDays(week,a==='week-prev'?-7:7);render();}
  if(a==='today'){selected=today;week=monday(today);render();}
  if(a==='select-day'){selected=b.dataset.date;render();}
  if(a==='exam-week'){week=monday(b.dataset.date);page='planner';render();}
  if(a==='task-new')taskModal(null,b.dataset.date??selected);
  if(a==='task-edit')taskModal(state.tasks.find(t=>t.id===tid));
  if(a==='toggle')await dispatch({type:'task-toggle',id:tid});
  if(a==='schedule-task'||a==='move-today'){if(await dispatch({type:'task-date',id:tid,date:a==='move-today'?today:selected}))toast('할 일과 플래너에 추가했어요.');}
  if(a==='task-delete')confirmModal('할 일을 삭제할까요?','연결된 플래너에서도 이 일정이 삭제돼요.',()=>dispatch({type:'task-delete',id:tid}));
  if(a==='exam-delete')confirmModal('시험 계획을 삭제할까요?','이 시험의 과목과 연결된 공부 일정이 함께 삭제돼요. 개인 할 일은 유지돼요.',()=>dispatch({type:'exam-delete',id:tid}));
  if(a==='exam-new')examModal();
  if(a==='exam-detail'){page='exams';render();}
  if(a==='subject-new')examModal(state.exams.find(e=>e.id===tid));
  if(a==='subject-settings')subjectSettings(state.subjects.find(s=>s.id===tid));
  if(a==='modal-close')$('#modal').close();
  if(a==='add-subject'){const form=$('#exam-form');$('#subjects').insertAdjacentHTML('beforeend',subjectFields($('#subjects').children.length));$('#subjects').lastElementChild.querySelector('[name="exam-date"]').value=form.elements.start.value;previewPlans(form);}
  if(a==='remove-subject')b.closest('.subject-fields').remove();
  if(a==='settings')showModal(`${modalHeader('YOUR WORKSPACE','설정 & 데이터')}<div class="settings-row"><div><strong>바탕화면 위젯</strong><p>주간 플래너 + 우측에 붙는 할 일 목록</p></div><button class="button" data-action="widgets">위젯 열기</button></div><div class="settings-row"><div><strong>데이터 백업</strong><p>현재 계획을 JSON 파일로 저장해요.</p></div><button class="button" data-action="backup">${icon('download')}백업</button></div><p class="helper">변경 내용은 이 PC에 자동 저장돼요. 위젯 상단의 핀을 누르면 다른 창 위에 고정할 수 있어요. 플래너 위젯은 제목 표시줄로 이동할 수 있어요.</p>${window.desktop?'<button class="text-button danger" data-action="quit">앱 완전히 종료</button>':''}`);
  if(a==='backup'){if(window.desktop){if(await window.desktop.backup())toast('백업 파일을 저장했어요.');}else{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`Monday-${today}.json`;anchor.click();URL.revokeObjectURL(url);toast('백업 파일을 저장했어요.');}}
});
document.addEventListener('submit',async e=>{if(e.target.id!=='quick-add')return;e.preventDefault();const title=new FormData(e.target).get('title').trim();if(!title)return;e.target.reset();if(await dispatch({type:'task-save',task:{id:id(),title,date:'',amount:null,unit:'',done:false,color:'lavender'}}))$('#quick-add input')?.focus();else $('#quick-add input').value=title;});
document.addEventListener('dragstart',e=>{const card=e.target.closest('.plan-card');if(card)e.dataTransfer.setData('text/plain',card.dataset.id);});
document.addEventListener('dragover',e=>{if(e.target.closest('.day-column')){e.preventDefault();e.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',async e=>{const day=e.target.closest('.day-column');if(day){e.preventDefault();await dispatch({type:'task-date',id:e.dataTransfer.getData('text/plain'),date:day.dataset.date});}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
try{if(window.desktop){state=await window.desktop.getState();window.desktop.onChange(next=>{state=next;render();});}else{const stored=localStorage.getItem('monday-state');state=stored?JSON.parse(stored):emptyState();if(!stored)localStorage.setItem('monday-state',JSON.stringify(state));window.addEventListener('storage',e=>{if(e.key==='monday-state'&&e.newValue){state=JSON.parse(e.newValue);render();}});}render();}catch(e){$('#app').textContent='저장된 계획을 불러오지 못했어요. 원본 데이터를 보존하고 앱을 다시 열어 주세요. '+e.message;}
setInterval(()=>{const now=dateKey();if(today!==now){if(selected===today)selected=now;today=now;render();}},30000);
